version: '3.11'

services:
  backend:
    image: user-transaction-admin
    build:
      context: src
    volumes:
      - ./src:/opt/backend/
      - ./poetry.lock:/opt/poetry.lock
      - ./pyproject.toml:/opt/pyproject.toml
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres:13-alpine
    command: -p 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"